"""Throwaway (plan step 6): old-vs-new trigger.py behaviour on identical,
production-realistic (keyword-keyed) seed data. Not a permanent tool.

Run from repo root:
  uv run --project api python process/features/narrative-mindshare/completed/narrative-keyword-keying_25-09-26/narrative-keyword-keying-diff_25-09-26.py
"""
from __future__ import annotations

import importlib.util
import sys
import tempfile
from pathlib import Path

TASK_DIR = Path(__file__).resolve().parent
REPO = TASK_DIR.parents[4]
sys.path.insert(0, str(REPO))

import pytest  # noqa: E402

from api.analytics import screener_board  # noqa: E402
from api.analytics.narrative import trigger as new_trigger  # noqa: E402
from api.data import cache, coingecko_adapter, pytrends_adapter, reddit_adapter  # noqa: E402
from api.tests.routers import test_narrative_categories_contract as contract  # noqa: E402

spec = importlib.util.spec_from_file_location("old_trigger_diff", TASK_DIR / "pre-fix-trigger_25-09-26.py")
old_trigger = importlib.util.module_from_spec(spec)
sys.modules["old_trigger_diff"] = old_trigger  # dataclass decorator needs the module registered
spec.loader.exec_module(old_trigger)
# The snapshot resolves its seed JSON relative to its own file; point it at the real one.
old_trigger.NARRATIVE_CATEGORIES_PATH = new_trigger.NARRATIVE_CATEGORIES_PATH

COINS = ("BTC", "ETH", "HYPE")
SOURCES = ("pytrends", "reddit", "coingecko")


def _run(module, symbols: list[str], root: Path) -> dict:
    seen: dict[str, dict] = {}
    with pytest.MonkeyPatch.context() as mp:
        mp.setattr(cache, "CACHE_ROOT", root)
        cache.bootstrap_cache_dirs()
        contract._seed_history()  # updated, keyword-keyed seed (step 5)
        mp.setattr(coingecko_adapter, "fetch_trending",
                   lambda *a, **k: coingecko_adapter.TrendingResult(symbols=list(symbols), as_of=contract.AS_OF, status="ok"))
        mp.setattr(pytrends_adapter, "fetch_trend",
                   lambda kw: pytrends_adapter.TrendResult(keyword=kw, value=1.0, as_of=contract.AS_OF, status="ok"))
        mp.setattr(reddit_adapter, "fetch_mentions",
                   lambda q, *a, **k: reddit_adapter.MentionResult(query=q, mention_count=1.0, as_of=contract.AS_OF, status="ok"))
        real = module.compute_trigger

        def spy(category_id, series_by_source, source_status):
            seen[category_id] = {s: (v is not None and not v.empty) for s, v in series_by_source.items()}
            return real(category_id, series_by_source, source_status)

        mp.setattr(module, "compute_trigger", spy)
        cats = module.assemble_narrative_categories(as_of=contract.AS_OF)
    by_id = {c.id: c for c in cats}
    return {
        "cats": by_id,
        "read": seen,
        "coins": {s: screener_board._coin_narrative_state(s, by_id) for s in COINS},
    }


def _fmt_read(read: dict) -> str:
    return ", ".join(f"{s}={'data' if read.get(s) else 'empty'}" for s in SOURCES)


def main() -> None:
    lines = [
        "---",
        "name: report:narrative-keyword-keying-diff",
        'description: "Old-vs-new trigger.py behaviour on identical keyword-keyed seed data (plan step 6)"',
        "date: 25-09-26",
        "metadata:",
        "  node_type: memory",
        "  type: report",
        "  feature: narrative-mindshare",
        "---",
        "",
        "# Narrative keyword-keying fix — before/after diff (plan step 6)",
        "",
        "Generated by `narrative-keyword-keying-diff_25-09-26.py`. OLD = `pre-fix-trigger_25-09-26.py` "
        "(reads every source by category_id); NEW = current `api/analytics/narrative/trigger.py`. Both run "
        f"against the SAME seed: the updated keyword-keyed `_seed_history()` from the contract test, "
        f"as_of={contract.AS_OF}, adapters stubbed exactly as the contract test does.",
        "",
        "Note: because the seed itself moved to keyword-keyed rows, the golden JSON the OLD code would "
        "produce against this seed may already differ from the committed golden file. The meaningful "
        "comparison is old-code vs new-code on identical realistic seed data, not old-fixture vs new-fixture.",
        "",
        "`source status` = adapter status passed through to `source_availability` (unchanged by the fix). "
        "`history read` = whether a non-empty history series actually reached `compute_trigger` "
        "(this is what `n_available` counts).",
        "",
    ]
    changed_total = 0
    with tempfile.TemporaryDirectory() as tmp:
        for name, symbols in contract.TRENDING_SCENARIOS.items():
            old = _run(old_trigger, symbols, Path(tmp) / f"old-{name}")
            new = _run(new_trigger, symbols, Path(tmp) / f"new-{name}")
            lines += [f"## Scenario `{name}` (trending: {', '.join(symbols)})", "",
                      "### Categories", "",
                      "| category | triggered (old -> new) | confirmed (old -> new) | trust_weight (old -> new) | "
                      "n_available (old -> new) | source status (old / new) | history read old | history read new |",
                      "|---|---|---|---|---|---|---|---|"]
            for cid in contract.SEED_IDS:
                o, n = old["cats"][cid], new["cats"][cid]
                on, nn = sum(old["read"][cid].values()), sum(new["read"][cid].values())
                st_o = ", ".join(f"{k}={v}" for k, v in sorted(o.source_availability.items()))
                st_n = ", ".join(f"{k}={v}" for k, v in sorted(n.source_availability.items()))
                changed = (o.triggered, o.confirmed, o.trust_weight, on) != (n.triggered, n.confirmed, n.trust_weight, nn)
                changed_total += changed
                mark = " **CHANGED**" if changed else ""
                lines.append(
                    f"| {cid}{mark} | {o.triggered} -> {n.triggered} | {o.confirmed} -> {n.confirmed} | "
                    f"{o.trust_weight} -> {n.trust_weight} | {on} -> {nn} | "
                    f"{st_o if st_o == st_n else st_o + ' / ' + st_n} | {_fmt_read(old['read'][cid])} | {_fmt_read(new['read'][cid])} |"
                )
            lines += ["", "### Screener coins (narrative_state / badge)", "",
                      "| coin | old | new | changed |", "|---|---|---|---|"]
            for sym in COINS:
                o, n = old["coins"][sym], new["coins"][sym]
                lines.append(f"| {sym} | {o} | {n} | {'yes' if o != n else 'no'} |")
            lines.append("")
    out = TASK_DIR / "narrative-keyword-keying_DIFF_25-09-26.md"
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {out} ({changed_total} category rows changed)")


if __name__ == "__main__":
    main()
